PUT http://localhost:3003/api/blogs/69bd9a60d913fae2aae86132
Content-Type: application/json

{
    "title": "Microservices and the First Law of Distributed Objects",
    "author": "Martin Fowler",
    "url": "https://martinfowler.com/articles/distributed-objects-microservices.html",
    "likes": 3
}