POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Liisa Marttinen",
    "number": "437.555.0000"
}

### status: 400
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "rr",
    "number": "040-243563"
}

### status: 400
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Liisa Marttinen"
}

### status: 400
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "519.555.0000"
}

### status: 409
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Liisa Marttinen",
    "number": "519.555.0000"
}