POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Liisa Marttinen",
    "number": "040-243563"
}

### status: 400
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Liisa Marttinen"
}

### status: 400
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "040-243563"
}

### status: 409
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "21-77-9832145"
}